# Generated by Django 3.1.7 on 2021-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link')),
                ('pub_date', models.DateField(verbose_name='Date Published')),
                ('cite', models.CharField(max_length=500, verbose_name='Citation')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('date_given', models.DateField(verbose_name='Date Given')),
                ('abstract', models.TextField(verbose_name='Abstract')),
            ],
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('GC', 'GCSE'), ('AL', 'A-Level'), ('U1', 'Undergraduate Year 1'), ('U2', 'Undergraduate Year 2'), ('U3', 'Undergraduate Year 3'), ('MA', 'Masters')], default='U1', max_length=2)),
                ('type', models.CharField(choices=[('TU', 'Tutor'), ('SU', 'Supervisor'), ('CT', 'Class Teacher'), ('LE', 'Lecturer')], default='CT', max_length=2)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('organisation_name', models.CharField(max_length=200, verbose_name='Organisation')),
                ('organisation_URL', models.URLField(verbose_name='Organisation URL')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
