on:
  push:
    tags:
      - '**.*.*'
name: docker-image
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        - name: echo GITHUB_REF
          run: echo ${GITHUB_REF}
        - name: 'Build and push image'
          uses: docker/login-action@v2
          with:
            registry: ${{ secrets.DOCKER_REPO }}
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - run: |
            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alex-site:${GITHUB_REF} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alex-site:latest ./
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/alex-site:${GITHUB_REF}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/alex-site:latest
