on:
  push:
    tags:
      - '**.*.*'
name: docker-image
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        - name: Set version env
          run: echo "RELEASE_VERSION=$(echo $GITHUB_REF | rev | cut -d '/' -f 1 | rev)" >> $GITHUB_ENV
        - name: Print release version
          run: echo ${{ env.RELEASE_VERSION }}
        - name: 'Build and push image'
          uses: docker/login-action@v2
          with:
            registry: ${{ secrets.DOCKER_REPO }}
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - run: |
            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alex-site:${{ env.RELEASE_VERSION }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alex-site:latest ./
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/alex-site:${{ env.RELEASE_VERSION }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/alex-site:latest
